name: DevCard

on:
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: DeCard
        uses: dailydotdev/action-devcard@2.2.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
          commit_message: "chore: update ${filename}"
